### ISSUE TITLE
How to run..?

### ISSUE THREAD

**Issue by ghost** [iWas-Coder/web-dl#3]
After a successfull installation, how to run the code and how to pass the video link to that..?

**Comment by ghost** [comment]
Give me a answer with the images please

**Comment by iWas-Coder** [comment]
Hello.

Thank you for your interest and for posting your issue here! It means a lot :)

In the repository's README.md file, there is a section for the usage of the script. Keep in mind that the application is still under heavy development and if the content is DRM protected, the decrypt portion of code is not finished yet.
The script expects a .MPD URL (XML layout) that describes to media (audio & video).

Thank you.
